### ISSUE TITLE
CleanUpOptions Bug

### ISSUE THREAD

**Issue by WaterKH** [WaterKH/KH3RandomizerWebsite#40]
> [kh3-randomizer] [2022-05-01 07:18:49] System.Collections.Generic.KeyNotFoundException: The given key 'None' was not present in the dictionary.
[kh3-randomizer] [2022-05-01 07:18:49]    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
[kh3-randomizer] [2022-05-01 07:18:49]    at KH3Randomizer.Data.RandomizerService.CleanUpOptions(Dictionary`2& randomizedOptions, Dictionary`2& copiedOptions, Dictionary`2 defaultOptions, Dictionary`2 randomizePools, Random random, Boolean canUseNone) in /src/KH3Randomizer/Data/RandomizerService.cs:line 1974

Seems like this is happening way too often. Investigate to see if we can alleviate these error logs.

**Comment by WaterKH** [comment]
Believe this will be addressed with the latest patch.
